os: linux
dist: focal

services:
    - docker

env:
    - ProjectsBase=build/xyteam
      
before_install:
    - docker pull xyteam/autobdd-run:2.1.0
    
script:
    - |
        cd .docker
        docker-compose run --rm autobdd-example-run "npm install" 
        docker-compose run --rm autobdd-example-run "npm start"
        docker-compose run --rm autobdd-example-run "npm run smoke-test"
        docker-compose run --rm autobdd-example-run "npm run api-test"
        docker-compose run --rm autobdd-example-run "npm run int-test"
        docker-compose run --rm autobdd-example-run "npm run e2e-test"