os: linux
dist: focal

services:
    - docker

env:
    - ProjectsBase=build/xyteam
      
before_install:
    - docker pull xyteam/autobdd-run:2.1.0
    
script:
    - |
        cd .docker
        docker-compose run --rm autobdd-example-run "--cucumberOpts.tagExpression='not @xfail and not @flicky and not @pending'" 