version: '3.5'
services:

  # dev container for developing autobdd test
  autobdd-example-dev:
    image: "xyteam/autobdd:${AutoBDD_Ver}"
    container_name: autobdd-example-dev
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - ${HOME}/${ProjectsBase:-Projects}/${ABDD_PROJECT}:/home/${USER}/Projects/AutoBDD/test-projects/${ABDD_PROJECT}:consistent
    ports:
      - "5924:5900"
      - "2224:22"
      - "8004:8000"
    environment:
      - USER=${USER}
      - ABDD_PROJECT=${ABDD_PROJECT}
      - HOSTOS=${HOSTOS}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - PASSWORD=${PASSWORD}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - RESOLUTION=1920x1200x24
    entrypoint: "/root/autobdd-dev.startup.sh"

  # run container for running autobdd test
  autobdd-example-run:
    image: "xyteam/autobdd:${AutoBDD_Ver}"
    container_name: autobdd-example-run
    shm_size: 1536M
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - ${HOME}/${ProjectsBase:-Projects}/${ABDD_PROJECT}:/home/${USER}/Projects/AutoBDD/test-projects/${ABDD_PROJECT}:consistent
    environment:
      - USER=${USER}
      - ABDD_PROJECT=${ABDD_PROJECT}
      - HOSTOS=${HOSTOS}
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      - PYTHONUNBUFFERED=1
      - REPORTDIR=${REPORTDIR}
      - MOVIE=${MOVIE}
      - SCREENSHOT=${SCREENSHOT}
      - SCREENSHOTREMARK=${SCREENSHOTREMARK}
    entrypoint: "/root/autobdd-run.startup.sh"

