jobs:
  build:
    docker:
      - image: 'xyteam/autobdd-run:2.1.0'
    working_directory: ~/Projects/AutoBDD/test-projects/AutoBDD-example
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm start
      - run: npm run smoke-test
      - run: npm run api-test
      - run: npm run int-test
      - run: npm run e2e-test

orbs:
  node: circleci/node@3.0.1

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
