version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  e2e-test:
    machine:
      - image: default
    working_directory: ~/Projects/AutoBDD-example/docker
    steps:
      - checkout:
        path: ~/Projects/AutoBDD-example
      - run:
        name: "run e2e test"
        command: |
          docker-compose run --rm autobdd-example-run
  workflows:
    test:
      jobs:
        - e2e-test